---
name: allcheckspassed # https://github.com/wechuli/allcheckspassed
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read # required for actions/checkout
concurrency:
  # yamllint disable-line rule:line-length
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  allcheckspassed:
    runs-on: ubuntu-latest
    permissions:
      checks: read # required to poll checks
      contents: read # required for actions/checkout
    steps:
      - uses: wechuli/allcheckspassed@b0eaef5be76003932c9520e2b3dd03c85cc43d87 # v2
